/**
 * A connection is split in two on purpose:
 *
 *   ConnectionConfig  — safe to persist, sync, export, commit to a repo.
 *   ConnectionSecret  — never touches config storage; lives behind the
 *                       SecretStore port (VS Code SecretStorage, OS keychain).
 *
 * Nothing in core ever writes a secret into a config object. Keeping these as
 * separate types means a mistake is a compile error rather than a leaked key in
 * someone's settings.json.
 */

/** Stable identifier for a provider implementation, e.g. `'s3'`, `'sftp'`. */
export type ProviderId = string;

/** Stable identifier for one configured connection. Opaque; generated by core. */
export type ConnectionId = string;

export interface ConnectionConfig {
  readonly id: ConnectionId;
  readonly providerId: ProviderId;
  /** Human-facing name shown in the tree and in pickers. */
  readonly label: string;
  /**
   * Provider-specific, non-sensitive settings: endpoint, region, bucket, host,
   * port, username, base path, TLS mode. Validated by the provider's schema,
   * not by core.
   */
  readonly settings: Readonly<Record<string, unknown>>;
  /** Path within the remote to treat as the connection root. Defaults to `/`. */
  readonly rootPath?: string | undefined;
  /**
   * A preset id or `#rrggbb`, so prod and staging are visually distinct. Read
   * it with `parseConnectionColor`, which ignores anything unrecognised.
   */
  readonly color?: string | undefined;
  /** When true, all writes are rejected before they reach the provider. */
  readonly readOnly?: boolean | undefined;
}

/**
 * Credential material. Shape is provider-defined; core only moves it between
 * the SecretStore port and the provider that asked for it.
 */
export type ConnectionSecret = Readonly<Record<string, unknown>>;

export type ConnectionState =
  | { readonly status: 'disconnected' }
  | { readonly status: 'connecting' }
  | { readonly status: 'connected'; readonly since: number }
  | { readonly status: 'error'; readonly error: string; readonly at: number };
